audio.exceptions.piperInitializationException=Failed to initialize Piper engine with data directory
audio.exceptions.voskInitializationException=Failed to initialize Vosk engine with model path
audio.exceptions.speakerWriteError=Failed to write audio data to speaker.
audio.exceptions.micReadError=Failed to read audio data from microphone.

audio.vosk.transcribing=Transcribing...
audio.vosk.initializing=Initializing Vosk engine...
