<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <name>audio</name>
    <description>
        The audio module with all the audio components of Nora.
    </description>
    <artifactId>audio</artifactId>
    <packaging>jar</packaging>
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>dev.masonroot</groupId>
        <artifactId>Nora</artifactId>
        <version>1.0.0-BETA</version>
    </parent>

    <properties>
        <logback.classic.version>1.5.12</logback.classic.version>
        <slf4j.version>2.0.16</slf4j.version>
    </properties>


    <dependencies>
        <dependency>
            <groupId>dev.masonroot</groupId>
            <artifactId>common</artifactId>
            <version>LATEST</version>
        </dependency>

        <dependency>
            <groupId>com.k2fsa.sherpa.onnx</groupId>
            <artifactId>sherpa-onnx</artifactId>
            <version>${sherpa.onnx.version}</version>
        </dependency>
    </dependencies>
</project>